CREATE TABLE REGION (
    id INTEGER PRIMARY KEY,
    name VARCHAR(40) UNIQUE NOT NULL,
    capital VARCHAR(40)
);

CREATE TABLE TOWNSHIP (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(40),
    region_id INTEGER NOT NULL
);